{{- if .Values.rbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-role"
rules:
  - apiGroups: ["", "extensions", "storage.k8s.io"]
    verbs: ["get", "list"]
    resources:
      - namespaces
      - pods
      - replicasets
      - deployments
      - replicationcontrollers
      - nodes
      - services
      - componentstatuses
      - storageclasses
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-role-binding"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
